services:
  # DATABASE A!!!
  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    # volumes:
    #   - mongo_data:/data/db
    expose:
      - "27017" # Exposed to other containers in the same network
    networks:
      - pipeline_network

  mongo-express:
    image: mongo-express
    container_name: mongo_web
    restart: always
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "8081:8081" # Only this is available to your host machine
    depends_on:
      - mongo
    networks:
      - pipeline_network

  # DATABASE B!!!
  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    expose:
      - "3306" # Exposed to other containers in the same network
    networks:
      - pipeline_network

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8080:8080" # Only this is available to your host machine
    depends_on:
      - mysql
    networks:
      - pipeline_network

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000" # S3 API
      - "9090:9090" # Web UI
    environment:
      MINIO_ROOT_USER: ${MINIO_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
    command: server /data --console-address ":9090"
    networks:
      - pipeline_network

  postgres_airflow:
    image: postgres:13
    container_name: postgres_airflow
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_AIRFLOW_USER}
      POSTGRES_PASSWORD: ${POSTGRES_AIRFLOW_PASSWORD}
      POSTGRES_DB: airflow
    expose:
      - "5432"
    networks:
      - pipeline_network

networks:
  pipeline_network:
    driver: bridge
# volumes:
#   mongo_data:
