services:
  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    # volumes:
    #   - mongo_data:/data/db
    expose:
      - "27017" # Exposed to other containers in the same network
    networks:
      - pipeline_network

  mongo-express:
    image: mongo-express
    container_name: mongo_web
    restart: always
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "8081:8081" # Only this is available to your host machine
    depends_on:
      - mongo
    networks:
      - pipeline_network

networks:
  pipeline_network:
    driver: bridge
# volumes:
#   mongo_data:
