analytics_project:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres_analytics
      user: dataAnalystA
      password: dataAnalystA
      port: 5432
      dbname: analytics
      schema: public
      threads: 4
